# Generated by Django 4.0.3 on 2022-06-15 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='header_images'),
            preserve_default=False,
        ),
    ]
