# Generated by Django 4.0.3 on 2022-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('UNDERGRADUATE', 'UNDERGRADUATE'), ('POSTGRADUATE', 'POSTGRADUATE'), ('DEGREE APPRENTICESHIP', 'DEGREE APPRENTICESHIP'), ('LEARNING AT WORK', 'LEARNING AT WORK'), ('DISTANT LEARNING', 'DISTANT LEARNING'), ('SHORT COURSES AND CPD', 'SHORT COURSE AND CPD')], default='UNDERGRADUATE', max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
    ]
